import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

function Header() {
	return (
		<div className="navbar">
			<a href="/" className="navbar-left">
				<img src="/ieee_mb_white.png" className="navbar-logo" />
				<h1 className="navbar-title">Edinburg Student Branch</h1>
			</a>
			<nav className="navbar-menu">
				<a href="/about">About Us</a>
				<a href="/events">Events</a>
				<a href="/membership">Membership</a>
				<a href="/leadership">Leadership</a>
				<a href="/collaborate">Collaborate</a>
				<a href="/contact">Contact Us</a>
			</nav>
		</div>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
