import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

function Footer() {
	return (
		<footer className="footer">
			<div className="footer-container">
				<div className="footer-logo">
					<a href="https://ieee.org" target="_blank">
						<img src="/ieee_mb_white.png" />
					</a>
				</div>

				<div className="footer-nav">
					<a href="/about">About Us</a>
					<a href="/membership">Membership</a>
					<a href="/contact">Contact Us</a>

					<a href="/events">Events</a>
					<a href="/leadership">Leadership</a>
					<a href="/collaborate">Collaborate</a>
				</div>
			</div>

			<div className="footer-socials">
				<a href="#" aria-label="Discord" className="discord">
					<img src="discord.svg" alt="Discord" />
				</a>
				<a href="#" aria-label="Instagram" className="instagram">
					<img src="instagram.svg" alt="Instagram" />
				</a>
				<a href="#" aria-label="Facebook" className="facebook">
					<img src="facebook.png" alt="Facebook" />
				</a>
			</div>

			<div className="footer-bottom">IEEE EDINBURG STUDENT BRANCH 2026</div>
		</footer>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}

				<Footer />
			</body>
		</html>
	);
}
